language: scala
sudo: false

scala:
  #  - 2.11.12
  - 2.12.6

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache

